version: "3.9"

services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: "drupal"
      MYSQL_DATABASE: "drupal"
      MYSQL_USER: "drupal"
      MYSQL_PASSWORD: "drupal"
  app:
    build: .
    ports:
      - "8585:8080"
    volumes:
      - "./scripts:/scripts"
      - "./workspace:/var/www/html"
