version: "3.8"

services:
  db:
    image: mysql:${MYSQL_VERSION}
    restart: unless-stopped
    env_file:
      - "./devcontainer.env"
    environment:
      cap_add: "SYS_NICE"
    ports:
      - "3306:3306"
    volumes:
      - "./config/mysql.cnf:/etc/mysql/conf.d/zmysql.cnf"
      - database:/var/lib/mysql
      # - "../dump/init.sql:/docker-entrypoint-initdb.d/mydb.sql"
  app:
    image: alchatti/drupal-devcontainer:${PHP_VERSION}
    network_mode: service:db
    env_file:
      - "./devcontainer.env"
    volumes:
      # - "pnpm-store:/home/vscode/.pnpm-store"
      - "acquia:/home/vscode/.acquia" # Acquia
      - "~/.wakatime.cfg:/home/vscode/.wakatime.cfg"
      - "~/.ssh:/home/vscode/.ssh"
      - "../.dev:/var/www/site-dev"
      - "..:/var/www/html"
    command: sleep infinity
volumes:
  database:
  acquia:
  # create >  docker volume create pnpm-store
  # pnpm-store:
    # external: true
