version: "3.8"

services:
  database:
    image: mysql:5.7
    restart: unless-stopped
    env_file:
      - "./devcontainer.env"
    environment:
      cap_add: "SYS_NICE"
    ports:
      - "3306:3306"
    volumes:
      - "./config/mysql.cnf:/etc/mysql/conf.d/zmysql.cnf"
      - database_store:/var/lib/mysql
      # - "../dump/init.sql:/docker-entrypoint-initdb.d/mydb.sql"
  app:
    image: alchatti/drupal-devcontainer:7.4
    env_file:
      - "./devcontainer.env"
    volumes:
      # - "pnpm-store:/home/vscode/.pnpm-store"
      - "~/.acquia:/home/vscode/.acquia" # Acquia Cloud Cli Share with host
      - "~/.ssh:/home/vscode/.ssh" # SSH Keys share with host
      - "~/.wakatime.cfg:/home/vscode/.wakatime.cfg" # Wakatime share with host
      - "../.dev:/var/www/site-dev"
      - "..:/var/www/html"
    command: sleep infinity
volumes:
  database_store:
  acquia:
  # create >  docker volume create pnpm-store
  # pnpm-store:
  #   external: true
