version: "3.8"

services:
  database:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: "db"
      MYSQL_USER: "drupal"
      MYSQL_PASSWORD: "drupalpassword"
      MYSQL_ROOT_PASSWORD: "rootpassword"
    cap_add:
      - SYS_NICE
    volumes:
      - "./config/mysql.cnf:/etc/mysql/conf.d/zmysql.cnf"
      - db:/var/lib/mysql
      # - "../dump/init.sql:/docker-entrypoint-initdb.d/mydb.sql"
  app:
    image: alchatti/drupal-devcontainer:8.1
    environment:
      MYSQL_USER: "drupal"
      MYSQL_PASSWORD: "drupalpassword"
    volumes:
      # - "pnpm-store:/home/vscode/.pnpm-store"
      - "~/.acquia:/home/vscode/.acquia" # Acquia Cloud Cli Share with host
      - "~/.ssh:/home/vscode/.ssh" # SSH Keys share with host
      - "~/.wakatime.cfg:/home/vscode/.wakatime.cfg" # Wakatime share with host
      - "../.dev:/var/www/site-dev"
      - "..:/var/www/html"
    command: sleep infinity
  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 18080:8080
volumes:
  db:
  acquia:
  # create >  docker volume create pnpm-store
  # pnpm-store:
  #   external: true
