version: "3.8"

services:
  database:
    image: mysql:8
    restart: unless-stopped
    env_file:
      - "./devcontainer.env"
    cap_add:
      - SYS_NICE
    ports:
      - "3306:3306"
    volumes:
      - "../.dev/mysql.cnf:/etc/mysql/conf.d/zmysql.cnf"
      - database:/var/lib/mysql
      # - "../dump/init.sql:/docker-entrypoint-initdb.d/mydb.sql"
  app:
    image: alchatti/drupal-devcontainer:8.2
    env_file:
      - "./devcontainer.env"
    volumes:
      - "~/.acquia:/home/vscode/.acquia" # Acquia Cloud Cli Share with host
      - "~/.ssh:/home/vscode/.ssh" # SSH Keys share with host
      - "~/.wakatime.cfg:/home/vscode/.wakatime.cfg" # Wakatime share with host
      - "../.dev:/var/www/site-dev"
      - "../.dev/drush.yml:/home/vscode/.drush/drush.yml"
      - "..:/var/www/html"
      # - "pnpm-store:/home/vscode/.pnpm-store"
    command: sleep infinity
volumes:
  database:
  # acquia:
  # create >  docker volume create pnpm-store
  # pnpm-store:
  #   external: true
