version: "3.8"

services:
  db:
    image: mysql:5.7
    restart: unless-stopped
    env_file:
      - "./devcontainer.env"
    environment:
      cap_add: "SYS_NICE"
    ports:
      - "3306:3306"
    volumes:
      - "./config/mysql.cnf:/etc/mysql/conf.d/zmysql.cnf"
      - database:/var/lib/mysql
      # - "../dump/init.sql:/docker-entrypoint-initdb.d/mydb.sql"
  app:
    image: alchatti/drupal-devcontainer:8.0
    network_mode: service:db
    env_file:
      - "./devcontainer.env"
    environment:
      AH_SITE_ENVIRONMENT: "dev" # Acquia Enviroment
    volumes:
      - "./config/dev.settings.php:/var/www/dev.settings.php"
      - "..:/var/www/html"
      - "pnpm-store:/home/vscode/.pnpm-store/"
      # - "~/.wakatime.cfg:/home/vscode/.wakatime.cfg:ro"
      # - "~/.acquia:/home/vscode/.acquia" # Acquia Cli Secrets
    command: sleep infinity
volumes:
  database:

  # create >  docker volume create pnpm-store
  pnpm-store:
    external: true
